version: '3.7'

services:
  postgres:
    container_name: footwedge-db-pg
    image: postgres:11.7
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=footwedge
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    container_name: footwedge-redis
    image: redis:5.0.9
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
  elasticsearch:
    container_name: footwedge-search
    image: elasticsearch:7.5.2
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      discovery.type: single-node
  search-service-api:
    container_name: search-service-api
    image: tjburn70/footwedge:search-service-api-latest
    build:
      context: ./lambdas/search-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - SEARCH_ENGINE_URI=http://footwedge-search
    volumes:
      - $HOME/.aws:/root/.aws:ro
    depends_on:
      - elasticsearch
  footwedge-api:
    container_name: footwedge-api
    image: tjburn70/footwedge:api-latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FOOTWEDGE_DATABASE_URI=postgresql://postgres:postgres@footwedge-db-pg/footwedge
      - SEARCH_SERVICE_API_BASE_URL=http://search-service-api:8001
      - HANDICAP_QUEUE_URL=https://sqs.us-east-2.amazonaws.com/753710783959/HandicapQueue
      - REDIS_URI=redis://footwedge-redis/0
    volumes:
      - $HOME/.aws:/root/.aws:ro
    depends_on:
      - postgres
      - redis
      - elasticsearch
  footwedge-web-client:
    container_name: footwedge-web-client
    image: tjburn70/footwedge:web-client-latest
    build:
      context: ./static
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - footwedge-api
