service: handicap-service
app: footwedge

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-2
  memorySize: 1024
  role: arn:aws:iam::753710783959:role/footwedge_lambda

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux


functions:
  calculateHandicap:
    handler: handler.lambda_handler
    module: src
    events:
      - sqs:
         arn: arn:aws:sqs:us-east-2:753710783959:HandicapQueue
         batchSize: 1
    environment:
      FOOTWEDGE_API_URL: "https://bd12304c815b.ngrok.io/api"

package:
  individually: true
  exclude:
    - a/**

# you can add CloudFormation resource templates here
resources:
  Resources:
    HandicapQueue:
      Type: AWS::SQS::Queue
      DependsOn: HandicapDeadLetterQueue
      Properties:
        QueueName: HandicapQueue
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - HandicapDeadLetterQueue
              - "Arn"
          maxReceiveCount: 5

    HandicapDeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: HandicapDeadLetterQueue
